import { Job, Application } from "./types";

const now = new Date();
const expires = new Date(now.getTime() + 365 * 24 * 60 * 60 * 1000).toISOString();

export const seedJobs: Job[] = [
  {
    id: "sample-1",
    posterName: "GOOD THINKING Jobs",
    posterEmail: "goodjobs@weareingoodco.com",
    companyName: "A Brand You'll Want to Work For",
    companyLogo: "",
    companyWebsite: "",
    title: "Chief Marketing Officer",
    department: "Executive/C-Suite",
    location: "New York, NY",
    locationType: "Hybrid",
    roleLevel: "C-Suite",
    salaryMin: 280000,
    salaryMax: 380000,
    description:
      "This is a sample listing. The real ones are coming.\n\nBut imagine: a brand that actually lets the CMO be a culture-maker, not just a funnel-optimizer. One that believes brand and performance aren't enemies. One that wants you in the room when the CEO is deciding what the company stands for, not just how to sell it.\n\nThat's the kind of role you'll find here. We built this board for the leaders who read GOOD THINKING every Sunday because they care about what's next, not just what's working.",
    requirements:
      "• You've built a brand people actually talk about\n• You can hold a room and also hold a spreadsheet\n• You've led teams through ambiguity (and made it look fun)\n• You read culture like other people read dashboards\n• You're here, which means you probably already qualify",
    externalApplyUrl: "",
    tier: "premium",
    approvalToken: "",
    status: "active",
    flaggedForNewsletter: true,
    createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: expires,
  },
  {
    id: "sample-2",
    posterName: "GOOD THINKING Jobs",
    posterEmail: "goodjobs@weareingoodco.com",
    companyName: "The Brand That Gets It",
    companyLogo: "",
    companyWebsite: "",
    title: "VP of Brand Strategy",
    department: "Brand",
    location: "Los Angeles, CA",
    locationType: "Hybrid",
    roleLevel: "VP",
    salaryMin: 220000,
    salaryMax: 280000,
    description:
      "This is a sample listing. Real roles are on their way.\n\nPicture this: a brand that knows the difference between a brand book and a brand. One that doesn't just want positioning, it wants a point of view. It wants someone who can see the cultural moment and build a brand that actually participates in it.\n\nWe created this job board because the best brand talent reads GOOD THINKING. And the best brands should be hiring here.",
    requirements:
      "• 12+ years building brands people remember (not just recognize)\n• You can translate a cultural shift into a brief by Tuesday\n• You've managed agencies without losing your mind or theirs\n• Strong opinions, loosely held\n• Bonus: you've ever described a brand as \"having a point of view\" and actually meant it",
    externalApplyUrl: "",
    tier: "premium",
    approvalToken: "",
    status: "active",
    flaggedForNewsletter: true,
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: expires,
  },
  {
    id: "sample-3",
    posterName: "GOOD THINKING Jobs",
    posterEmail: "goodjobs@weareingoodco.com",
    companyName: "A Very Good Agency",
    companyLogo: "",
    companyWebsite: "",
    title: "Strategy Director",
    department: "Strategy",
    location: "New York, NY",
    locationType: "Remote",
    roleLevel: "Director",
    salaryMin: 165000,
    salaryMax: 200000,
    description:
      "This is a sample listing. The real ones will be worth the wait.\n\nSomewhere out there is an agency that wants a strategist who reads culture, not just category reports. One where the strategy team is in the room before the brief is written, not after. Where your references can come from a podcast, a gallery, or a grocery store aisle.\n\nThat agency is going to post here. And you're going to want to see it.",
    requirements:
      "• 8+ years in brand strategy or planning\n• You can run a discovery workshop that people actually enjoy\n• You present to C-suites without losing the human voice\n• Your strategy decks don't put people to sleep\n• You notice things other people scroll past",
    externalApplyUrl: "",
    tier: "standard",
    approvalToken: "",
    status: "active",
    flaggedForNewsletter: false,
    createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: expires,
  },
  {
    id: "sample-4",
    posterName: "GOOD THINKING Jobs",
    posterEmail: "goodjobs@weareingoodco.com",
    companyName: "A DTC Brand With Taste",
    companyLogo: "",
    companyWebsite: "",
    title: "Senior Content Strategist",
    department: "Creative",
    location: "Austin, TX",
    locationType: "Remote",
    roleLevel: "Senior",
    salaryMin: 115000,
    salaryMax: 140000,
    description:
      "This is a sample listing. Real roles coming soon.\n\nThe kind of content strategist we're talking about doesn't just plan a content calendar. They know why a certain story works right now, what the brand should be saying this week, and why the obvious angle is the wrong one.\n\nYou write like a human. You think like a strategist. You scroll like a cultural anthropologist. The brands posting here will be looking for exactly that.",
    requirements:
      "• 6+ years in content strategy or editorial\n• A portfolio that reads like a person wrote it (because you did)\n• You can explain why something works, not just that it does\n• You know the difference between trending and actually interesting\n• Bonus: you've ever killed your own idea because a better one walked in",
    externalApplyUrl: "",
    tier: "standard",
    approvalToken: "",
    status: "active",
    flaggedForNewsletter: false,
    createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: expires,
  },
  {
    id: "sample-5",
    posterName: "GOOD THINKING Jobs",
    posterEmail: "goodjobs@weareingoodco.com",
    companyName: "A Studio That Gives a Damn",
    companyLogo: "",
    companyWebsite: "",
    title: "Brand Designer",
    department: "Creative",
    location: "Brooklyn, NY",
    locationType: "On-site",
    roleLevel: "Mid",
    salaryMin: 85000,
    salaryMax: 100000,
    description:
      "This is a sample listing. Real ones are on the way.\n\nThe studios and in-house teams posting here will be the ones where design isn't decoration. Where the brand designer sits next to the strategist, not three Slack channels away. Where the work actually looks like the culture it's speaking to.\n\nThis board is new. The roles are coming. And they'll be the kind that make you want to update your portfolio.",
    requirements:
      "• 3-5 years of brand design that you're actually proud of\n• A portfolio that shows identity systems, not just pretty decks\n• Figma is second nature. Taste is first.\n• You care about the why as much as the what\n• You're the person your friends text when they need a restaurant rec or a font opinion",
    externalApplyUrl: "",
    tier: "free",
    approvalToken: "",
    status: "active",
    flaggedForNewsletter: false,
    createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: expires,
  },
  {
    id: "sample-6",
    posterName: "GOOD THINKING Jobs",
    posterEmail: "goodjobs@weareingoodco.com",
    companyName: "A Media Team That Thinks",
    companyLogo: "",
    companyWebsite: "",
    title: "Media Planner",
    department: "Media",
    location: "Chicago, IL",
    locationType: "Hybrid",
    roleLevel: "Mid",
    salaryMin: 72000,
    salaryMax: 90000,
    description:
      "This is a sample listing. Real media roles are coming.\n\nWe're talking about the agencies and brands where media planning isn't just a spreadsheet exercise. Where someone actually thinks about context, not just CPMs. Where the planner gets a seat at the strategy table because they understand that where something runs matters as much as what it says.\n\nThose teams are going to find their next hire here.",
    requirements:
      "• 2-4 years in media planning (agency or in-house)\n• You can talk about reach and also about relevance\n• You're curious about where culture shows up, not just where impressions live\n• Strong with data, stronger with judgment\n• You've questioned a media plan at least once because it felt wrong, even if the numbers said otherwise",
    externalApplyUrl: "",
    tier: "free",
    approvalToken: "",
    status: "active",
    flaggedForNewsletter: false,
    createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: expires,
  },
  {
    id: "sample-7",
    posterName: "GOOD THINKING Jobs",
    posterEmail: "goodjobs@weareingoodco.com",
    companyName: "A Company Rewriting the Rules",
    companyLogo: "",
    companyWebsite: "",
    title: "Head of Marketing Operations",
    department: "Operations",
    location: "Denver, CO",
    locationType: "Remote",
    roleLevel: "Director",
    salaryMin: 155000,
    salaryMax: 190000,
    description:
      "This is a sample listing. Real ops roles are coming.\n\nMarketing ops is quietly becoming one of the most interesting roles in the building. The person who makes the machine work. Who sees the full picture when everyone else is stuck in their channel. Who knows that the best creative in the world doesn't matter if nobody can find it, measure it, or learn from it.\n\nThe companies posting here will know that.",
    requirements:
      "• 7+ years in marketing ops or revenue ops\n• You've built a martech stack and also torn one down\n• You think in systems but communicate in plain English\n• You can make a CMO and a CFO both happy (simultaneously)\n• You believe operations is a creative act",
    externalApplyUrl: "",
    tier: "standard",
    approvalToken: "",
    status: "active",
    flaggedForNewsletter: false,
    createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: expires,
  },
  {
    id: "sample-8",
    posterName: "GOOD THINKING Jobs",
    posterEmail: "goodjobs@weareingoodco.com",
    companyName: "A Brand Worth Leading",
    companyLogo: "",
    companyWebsite: "",
    title: "Chief Brand Officer",
    department: "Executive/C-Suite",
    location: "Miami, FL",
    locationType: "On-site",
    roleLevel: "C-Suite",
    salaryMin: 300000,
    salaryMax: 400000,
    description:
      "This is a sample listing. But the real CBO roles coming to this board will be worth paying attention to.\n\nThe brands that post here are the ones that believe the brand leader should be in the room for every big decision, not just the campaign ones. They want someone who understands that brand isn't a department. It's the whole thing.\n\nWe built this board where your next hire reads. If you're a CBO candidate reading this on a Sunday night after the GOOD THINKING letter, you're in the right place.",
    requirements:
      "• 15+ years building brands people genuinely love\n• You can make the board care about brand as much as the creative team does\n• You've navigated a rebrand, a crisis, or both (ideally not at the same time)\n• You read culture fluently and translate it into business decisions\n• You still get excited about a great campaign",
    externalApplyUrl: "",
    tier: "premium",
    approvalToken: "",
    status: "active",
    flaggedForNewsletter: true,
    createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    expiresAt: expires,
  },
];

export const seedApplications: Application[] = [];
